Basic routes, logic, and design
union-platform/union-mobile pull request #50
Opened 2023-04-14 16:35 UTC by rexolion

## Related issue(s)

Resolves: #

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary: [README](../tree/master/README.md), Haddock
  - [ ] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users.

#### Before merging (mandatory)

- [ ] My commits comply with [the policy used in Union](https://github.com/union-platform/guides/blob/master/commits.md) and code complies with the [styles guide](https://github.com/union-platform/guides/blob/master/README.md#programming-languages).
- [ ] Check __target__  branch of PR is set correctly

2023-04-14 17:02 UTC, worm2fed commented
great job! A lot of review for me 😅😭

2023-04-14 18:18 UTC, rexolion commented
@worm2fed brief demo of what has been done (spoiler: a lot!)

Tests will be in other commits.

https://youtu.be/TBVb9FdcMXE

2023-04-14 22:51 UTC, worm2fed requested changes
wow, good job

2023-04-14 22:51 UTC, worm2fed commented on lib/mocks/interests_mock.dart
> +const InterestsMock = [
it's in DB, there is endpoint to get it or create a new one if it is not in list
but we can keep your list and use as fixture at backend side

2023-04-14 22:51 UTC, worm2fed commented on lib/models/user_profile_model.dart
> +        json['activatedAt'] != null ? json['activatedAt'] as String : null;
uf.. is there a shortcut for this?

2023-04-14 22:51 UTC, worm2fed commented on lib/models/user_profile_model.dart
> +    pk = json['pk'] != null ? json['pk'] as int : null;
both cannot be null

2023-04-14 22:51 UTC, worm2fed commented on lib/models/user_profile_model.dart
> +    accountId = json['accountId'] != null ? json['accountId'] as String : null;
it cannot be null

2023-04-14 22:51 UTC, worm2fed commented on lib/models/user_profile_model.dart
> +    name = json['name'] != null ? json['name'] as String : null;
it cannot be null

2023-04-14 22:51 UTC, worm2fed commented on lib/screens/activity/create_team.dart
> +var _currencies = [
currencies?))
for scope there is endpoint in DB (without creation one, I have fixture)

2023-04-14 22:51 UTC, worm2fed commented on lib/screens/login.dart
> +                  phoneSubmitted
we switched to email and OTP from it

2023-04-14 22:51 UTC, worm2fed commented on lib/widgets/project_card.dart
> +    );
a lot of brackets))

2023-04-14 22:52 UTC, worm2fed commented
@rexolion pls, rename your first commit as described here: https://www.conventionalcommits.org/en/v1.0.0/

2023-04-17 11:26 UTC, rexolion commented on .gitignore
> +.DS_Store
What if someone fucked up that one? I want a fool proof system

2023-04-17 11:31 UTC, rexolion commented on android/app/build.gradle
> +    flutterVersionName = '1.0'
It in pubspec for android (and inner flutter) and in Runner for ios

2023-04-17 11:32 UTC, rexolion commented on android/app/build.gradle
> +    flutterVersionName = '1.0'
I set the version you like

2023-04-17 11:33 UTC, rexolion commented on android/app/src/main/kotlin/com/example/app/MainActivity.kt
> +package com.example.app
'Truly' renaming the app it's a task for a different commit

2023-04-17 11:33 UTC, rexolion commented on android/app/src/main/res/mipmap-hdpi/ic_launcher.png
Branding the app it's a task for a different commit

2023-04-17 11:37 UTC, rexolion commented on lib/mocks/gallery_mock.dart
I don't get the question. See the demo, it's the gallery of photos in the project entity.

2023-04-17 11:39 UTC, rexolion commented on lib/mocks/interests_mock.dart
> +const InterestsMock = [
It's just the mock for the initial commit of routes, I need some list to use it in UI. Surely we will get it through the API in future commits

2023-04-17 11:39 UTC, rexolion commented on lib/models/user_profile_model.dart
> +        json['activatedAt'] != null ? json['activatedAt'] as String : null;
No, dart is strictly null safe

2023-04-17 11:47 UTC, rexolion commented on lib/models/user_profile_model.dart
> +    pk = json['pk'] != null ? json['pk'] as int : null;
ok

2023-04-17 11:47 UTC, rexolion commented on lib/models/user_profile_model.dart
> +    name = json['name'] != null ? json['name'] as String : null;
mission and motivation could be null, name not

2023-04-17 11:54 UTC, rexolion commented on lib/screens/activity/create_team.dart
> +var _currencies = [
Renamed it, API integration in other commit

2023-04-17 11:57 UTC, worm2fed commented on android/app/build.gradle
> +    flutterVersionName = '1.0'
Can we make one source of truth? To specify it in 1 place, not in 3

2023-04-17 11:59 UTC, worm2fed commented on lib/models/user_profile_model.dart
> +    name = json['name'] != null ? json['name'] as String : null;
Yes

2023-04-17 12:15 UTC, rexolion commented on android/app/build.gradle
> +    flutterVersionName = '1.0'
Only in two, ios and android, as I know no, cannot specify it in one place.

2023-04-17 12:15 UTC, rexolion commented on android/app/build.gradle
> +    flutterVersionName = '1.0'
Here is constant used

2023-04-17 12:20 UTC, rexolion commented
@worm2fed is it counts as BREAKING CHANGE?

2023-04-17 19:37 UTC, rexolion commented on lib/screens/login.dart
> +                  phoneSubmitted
Basic initial setup commit, I will fix it in other commit

2023-04-17 19:50 UTC, worm2fed commented
@rexolion can I push to your PR?

2023-04-17 19:51 UTC, rexolion commented
@worm2fed Ok, if needed :)

2023-04-18 09:44 UTC, rexolion commented
@worm2fed I want to continue development in my spare time, so if it takes time for you to commit, let's do that in a different PR

2023-04-18 09:57 UTC, worm2fed commented
@rexolion 10 min

2023-04-18 10:24 UTC, worm2fed commented on android/app/src/debug/AndroidManifest.xml
should it be in ignore?

There is this in ignore`/android/app/debug`
but this is not: `/android/src/app/debug`

is it correct?

2023-04-18 10:24 UTC, worm2fed approved these changes

2023-04-18 10:33 UTC, rexolion commented on android/app/src/debug/AndroidManifest.xml
yep

2023-04-18 10:39 UTC, rexolion commented
@worm2fed You cannot add comments inside storyboard files — build fails, it's the guts of the ios, that's why I added the license in a different file.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/20303265/232752499-8d4ee900-57d0-4499-a6cc-d6d400b1153d.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/20303265/232752597-f5b24109-1031-438f-8feb-1a9a0179dcc6.png">

2023-04-18 10:40 UTC, worm2fed commented
@rexolion mm.. but build is done without errors

2023-04-18 10:41 UTC, rexolion commented
> @rexolion mm.. but build is done without errors

It's Android's build in Github action

2023-04-18 10:41 UTC, worm2fed commented
@rexolion will push fix now

2023-04-18 10:42 UTC, worm2fed commented
@rexolion what about plist?

2023-04-18 10:44 UTC, rexolion commented
> @rexolion what about plist?

Only storyboard files didn't like that

2023-04-18 11:22 UTC, merged